//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDiagram")]

namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	/// <summary>
	/// DomainClass IGGORCJCFProyectoIPSDiagram
	/// Description for UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDiagram.DisplayName", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDiagram.Description", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("55137c92-17c0-4e4a-bfbb-c090564087ff")]
	public partial class IGGORCJCFProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Diagram styles
		/// <summary>
		/// Initializes style set resources for this shape type
		/// </summary>
		/// <param name="classStyleSet">The style set for this shape class</param>
		protected override void InitializeResources(DslDiagrams::StyleSet classStyleSet)
		{
			base.InitializeResources(classStyleSet);
			
			// Fill brush settings for this shape.
			DslDiagrams::BrushSettings backgroundBrush = new DslDiagrams::BrushSettings();
			backgroundBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.MistyRose);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramBackground, backgroundBrush);
		
			// Text brush settings for this shape.
			DslDiagrams::BrushSettings textBrush = new DslDiagrams::BrushSettings();
			textBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.Firebrick);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramText, textBrush);
		
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrinMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrinMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.Boton)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.BotonMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.BotonMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenu)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenuMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenuMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTexto)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.CheckBox)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.CheckboxMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.CheckboxMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTexto)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.Menu)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MenuMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MenuMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinal)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaEstadoFinal newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaEstadoFinal(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.Clase)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesComponente)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ItemReferencesVentana)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaItem_Ventana newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaItem_Ventana(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.Componente)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteMetafora newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteMetafora(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesMenu4)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesItem4)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ItemReferencesEstadoFinal)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaEstadoFinal_Item newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaEstadoFinal_Item(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesItem)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteConnector newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesEntradaDeDatos)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteConnector newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesMenu)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteConnector newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesVentana4)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesEntradaDeDatos)
			{
				global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos newShape = new global::UPM_IPS.IGGORCJCFProyectoIPS.MetaforaClase_Elementos(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecMetafora.DecoratorsInitialized += VentanaSecMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrinMetafora.DecoratorsInitialized += VentanaPrinMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.MenuMetafora.DecoratorsInitialized += MenuMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.BotonMetafora.DecoratorsInitialized += BotonMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenuMetafora.DecoratorsInitialized += ItemMenuMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseMetafora.DecoratorsInitialized += ClaseMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.CheckboxMetafora.DecoratorsInitialized += CheckboxMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoMetafora.DecoratorsInitialized += AreaDeTextoMetaforaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoMetafora.DecoratorsInitialized += CampoDeTextoMetaforaDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for VentanaSecMetafora.
		/// </summary>
		internal static partial class VentanaSecMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for VentanaSecMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.altoCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alto").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombre").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.anchoCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ancho").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria.modalDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "modal").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for VentanaPrinMetafora.
		/// </summary>
		internal static partial class VentanaPrinMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for VentanaPrinMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.altoCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alto").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.anchoCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ancho").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MenuMetafora.
		/// </summary>
		internal static partial class MenuMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MenuMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Menu.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "titulo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for BotonMetafora.
		/// </summary>
		internal static partial class BotonMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for BotonMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Item.tituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ItemMenuMetafora.
		/// </summary>
		internal static partial class ItemMenuMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ItemMenuMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Item.tituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "titulo").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Item.tituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "titulo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ClaseMetafora.
		/// </summary>
		internal static partial class ClaseMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ClaseMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.Clase.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CheckboxMetafora.
		/// </summary>
		internal static partial class CheckboxMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CheckboxMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos.TituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Titulo").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos.TituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Titulo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AreaDeTextoMetafora.
		/// </summary>
		internal static partial class AreaDeTextoMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AreaDeTextoMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos.TituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Titulo").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos.TituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Titulo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CampoDeTextoMetafora.
		/// </summary>
		internal static partial class CampoDeTextoMetaforaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CampoDeTextoMetafora.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos.TituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Titulo").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos.TituloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Titulo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceItem_VentanaToolConnectAction enlaceItem_VentanaToolConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceEstadoFinal_ItemToolConnectAction enlaceEstadoFinal_ItemToolConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_VentanaConnectAction enlaceClase_VentanaConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ItemConnectAction enlaceClase_ItemConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_MenuConnectAction enlaceClase_MenuConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ComponenteConnectAction enlaceClase_ComponenteConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_EntradaDeDatosConnectAction enlaceClase_EntradaDeDatosConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_itemConnectAction enlaceComponente_itemConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_EntradaDeDatosConnectAction enlaceComponente_EntradaDeDatosConnectAction;
		private global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_MenuConnectAction enlaceComponente_MenuConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceItem_VentanaToolFilterString))
				{
					if (this.enlaceItem_VentanaToolConnectAction == null)
					{
						this.enlaceItem_VentanaToolConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceItem_VentanaToolConnectAction(this);
						this.enlaceItem_VentanaToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceItem_VentanaToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceEstadoFinal_ItemToolFilterString))
				{
					if (this.enlaceEstadoFinal_ItemToolConnectAction == null)
					{
						this.enlaceEstadoFinal_ItemToolConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceEstadoFinal_ItemToolConnectAction(this);
						this.enlaceEstadoFinal_ItemToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceEstadoFinal_ItemToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceClase_VentanaFilterString))
				{
					if (this.enlaceClase_VentanaConnectAction == null)
					{
						this.enlaceClase_VentanaConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_VentanaConnectAction(this);
						this.enlaceClase_VentanaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceClase_VentanaConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceClase_ItemFilterString))
				{
					if (this.enlaceClase_ItemConnectAction == null)
					{
						this.enlaceClase_ItemConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ItemConnectAction(this);
						this.enlaceClase_ItemConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceClase_ItemConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceClase_MenuFilterString))
				{
					if (this.enlaceClase_MenuConnectAction == null)
					{
						this.enlaceClase_MenuConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_MenuConnectAction(this);
						this.enlaceClase_MenuConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceClase_MenuConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceClase_ComponenteFilterString))
				{
					if (this.enlaceClase_ComponenteConnectAction == null)
					{
						this.enlaceClase_ComponenteConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ComponenteConnectAction(this);
						this.enlaceClase_ComponenteConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceClase_ComponenteConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceClase_EntradaDeDatosFilterString))
				{
					if (this.enlaceClase_EntradaDeDatosConnectAction == null)
					{
						this.enlaceClase_EntradaDeDatosConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_EntradaDeDatosConnectAction(this);
						this.enlaceClase_EntradaDeDatosConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceClase_EntradaDeDatosConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceComponente_itemFilterString))
				{
					if (this.enlaceComponente_itemConnectAction == null)
					{
						this.enlaceComponente_itemConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_itemConnectAction(this);
						this.enlaceComponente_itemConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceComponente_itemConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceComponente_EntradaDeDatosFilterString))
				{
					if (this.enlaceComponente_EntradaDeDatosConnectAction == null)
					{
						this.enlaceComponente_EntradaDeDatosConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_EntradaDeDatosConnectAction(this);
						this.enlaceComponente_EntradaDeDatosConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceComponente_EntradaDeDatosConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper.EnlaceComponente_MenuFilterString))
				{
					if (this.enlaceComponente_MenuConnectAction == null)
					{
						this.enlaceComponente_MenuConnectAction = new global::UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_MenuConnectAction(this);
						this.enlaceComponente_MenuConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.enlaceComponente_MenuConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.enlaceItem_VentanaToolConnectAction != null)
					{
						this.enlaceItem_VentanaToolConnectAction.Dispose();
						this.enlaceItem_VentanaToolConnectAction = null;
					}
					if(this.enlaceEstadoFinal_ItemToolConnectAction != null)
					{
						this.enlaceEstadoFinal_ItemToolConnectAction.Dispose();
						this.enlaceEstadoFinal_ItemToolConnectAction = null;
					}
					if(this.enlaceClase_VentanaConnectAction != null)
					{
						this.enlaceClase_VentanaConnectAction.Dispose();
						this.enlaceClase_VentanaConnectAction = null;
					}
					if(this.enlaceClase_ItemConnectAction != null)
					{
						this.enlaceClase_ItemConnectAction.Dispose();
						this.enlaceClase_ItemConnectAction = null;
					}
					if(this.enlaceClase_MenuConnectAction != null)
					{
						this.enlaceClase_MenuConnectAction.Dispose();
						this.enlaceClase_MenuConnectAction = null;
					}
					if(this.enlaceClase_ComponenteConnectAction != null)
					{
						this.enlaceClase_ComponenteConnectAction.Dispose();
						this.enlaceClase_ComponenteConnectAction = null;
					}
					if(this.enlaceClase_EntradaDeDatosConnectAction != null)
					{
						this.enlaceClase_EntradaDeDatosConnectAction.Dispose();
						this.enlaceClase_EntradaDeDatosConnectAction = null;
					}
					if(this.enlaceComponente_itemConnectAction != null)
					{
						this.enlaceComponente_itemConnectAction.Dispose();
						this.enlaceComponente_itemConnectAction = null;
					}
					if(this.enlaceComponente_EntradaDeDatosConnectAction != null)
					{
						this.enlaceComponente_EntradaDeDatosConnectAction.Dispose();
						this.enlaceComponente_EntradaDeDatosConnectAction = null;
					}
					if(this.enlaceComponente_MenuConnectAction != null)
					{
						this.enlaceComponente_MenuConnectAction.Dispose();
						this.enlaceComponente_MenuConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// IGGORCJCFProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x55137c92, 0x17c0, 0x4e4a, 0xbf, 0xbb, 0xc0, 0x90, 0x56, 0x40, 0x87, 0xff);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IGGORCJCFProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IGGORCJCFProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Boton), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTexto), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.CheckBox), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTexto), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesEntradaDeDatos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesItem), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesMenu4), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesItem4), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesVentana4), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Componente), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ItemReferencesVentana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesComponente), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Clase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Menu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ItemReferencesEstadoFinal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesEntradaDeDatos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria)
				{
					parentElement = GetParentForVentanaSecundaria((global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal)
				{
					parentElement = GetParentForVentanaPrincipal((global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.Boton)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForBoton(Boton childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForBoton((global::UPM_IPS.IGGORCJCFProyectoIPS.Boton)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenu)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForItemMenu(ItemMenu childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForItemMenu((global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenu)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTexto)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForAreaDeTexto(AreaDeTexto childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForAreaDeTexto((global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTexto)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.CheckBox)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForCheckBox(CheckBox childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForCheckBox((global::UPM_IPS.IGGORCJCFProyectoIPS.CheckBox)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTexto)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForCampoDeTexto(CampoDeTexto childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForCampoDeTexto((global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTexto)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.Componente)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForComponente(Componente childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForComponente((global::UPM_IPS.IGGORCJCFProyectoIPS.Componente)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.Clase)
				{
					parentElement = GetParentForClase((global::UPM_IPS.IGGORCJCFProyectoIPS.Clase)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinal)
				{
					parentElement = GetParentForEstadoFinal((global::UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinal)childElement);
				} else
				if(childElement is global::UPM_IPS.IGGORCJCFProyectoIPS.Menu)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForMenu(Menu childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForMenu((global::UPM_IPS.IGGORCJCFProyectoIPS.Menu)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas GetParentForVentanaSecundaria( global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria root )
			{
				// Segments 0 and 1
				global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas result = root.TapizVentanas1;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas GetParentForVentanaPrincipal( global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal root )
			{
				// Segments 0 and 1
				global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas result = root.TapizVentanas;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas GetParentForEstadoFinal( global::UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinal root )
			{
				// Segments 0 and 1
				global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas result = root.TapizEstado;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas GetParentForClase( global::UPM_IPS.IGGORCJCFProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanas result = root.TapizVentanas2;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Menu), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Item), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.Clase), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.altoCalculadaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecMetafora.FindVentanaSecMetaforaDecorator("alto");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrinMetafora.FindVentanaPrinMetaforaDecorator("alto");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecMetafora.FindVentanaSecMetaforaDecorator("nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrinMetafora.FindVentanaPrinMetaforaDecorator("Nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.IGGORCJCFProyectoIPS.Ventana.anchoCalculadaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecMetafora.FindVentanaSecMetaforaDecorator("ancho");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrinMetafora.FindVentanaPrinMetaforaDecorator("ancho");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.IGGORCJCFProyectoIPS.Menu.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.MenuMetafora.FindMenuMetaforaDecorator("titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.Menu.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.IGGORCJCFProyectoIPS.Item.tituloDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenuMetafora.FindItemMenuMetaforaDecorator("titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenu.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.IGGORCJCFProyectoIPS.Clase.NombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseMetafora.FindClaseMetaforaDecorator("Nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.Clase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.IGGORCJCFProyectoIPS.EntradaDeDatos.TituloDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoMetafora.FindAreaDeTextoMetaforaDecorator("Titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTexto.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.CheckboxMetafora.FindCheckboxMetaforaDecorator("Titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.CheckBox.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoMetafora.FindAreaDeTextoMetaforaDecorator("Titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTexto.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.CheckboxMetafora.FindCheckboxMetaforaDecorator("Titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.CheckBox.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoMetafora.FindCampoDeTextoMetaforaDecorator("Titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTexto.DomainClassId);
					}
					decorator = global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoMetafora.FindCampoDeTextoMetaforaDecorator("Titulo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTexto.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ItemReferencesVentana), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ItemReferencesEstadoFinal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesVentana4), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesItem4), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesMenu4), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesItem), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesEntradaDeDatos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ComponenteReferencesMenu), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesComponente), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ClaseReferencesEntradaDeDatos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDiagram diagram = linkShape.Diagram as global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
