//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	/// <summary>
	/// DomainModel IGGORCJCFProyectoIPSDomainModel
	/// Description for UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("2b87ccb7-95cf-4e1a-a636-10d8a79b0d2d")]
	public partial class IGGORCJCFProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// IGGORCJCFProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x2b87ccb7, 0x95cf, 0x4e1a, 0xa6, 0x36, 0x10, 0xd8, 0xa7, 0x9b, 0x0d, 0x2d);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public IGGORCJCFProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(TapizVentanas),
				typeof(VentanaPrincipal),
				typeof(Ventana),
				typeof(VentanaSecundaria),
				typeof(Boton),
				typeof(Menu),
				typeof(ItemMenu),
				typeof(Item),
				typeof(EstadoFinal),
				typeof(Clase),
				typeof(EntradaDeDatos),
				typeof(CampoDeTexto),
				typeof(AreaDeTexto),
				typeof(CheckBox),
				typeof(Componente),
				typeof(TapizVentanasHasVentanaPrincipal),
				typeof(TapizVentanasHasVentanaSecundaria),
				typeof(VentanaHasBotonPertenece),
				typeof(VentanaHasMenuPertenece),
				typeof(MenuHasItemPerteneceMenu),
				typeof(ItemReferencesVentana),
				typeof(TapizVentanasHasEstadoFinal),
				typeof(ItemReferencesEstadoFinal),
				typeof(ItemReferencesClase),
				typeof(TapizVentanasHasClase),
				typeof(ClaseReferencesVentana4),
				typeof(ClaseReferencesItem4),
				typeof(ClaseReferencesMenu4),
				typeof(VentanaHasEntradaDeDatos),
				typeof(VentanaHasComponente),
				typeof(ComponenteReferencesItem),
				typeof(ComponenteReferencesEntradaDeDatos),
				typeof(ComponenteReferencesMenu),
				typeof(ClaseReferencesComponente),
				typeof(ClaseReferencesEntradaDeDatos),
				typeof(IGGORCJCFProyectoIPSDiagram),
				typeof(MetaforaItem_Ventana),
				typeof(MetaforaEstadoFinal_Item),
				typeof(MetaforaClase_Elementos),
				typeof(ComponenteConnector),
				typeof(ComponenteMetafora),
				typeof(VentanaSecMetafora),
				typeof(VentanaPrinMetafora),
				typeof(MenuMetafora),
				typeof(BotonMetafora),
				typeof(ItemMenuMetafora),
				typeof(MetaforaEstadoFinal),
				typeof(ClaseMetafora),
				typeof(CampoDeTextoMetafora),
				typeof(AreaDeTextoMetafora),
				typeof(CheckboxMetafora),
				typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(TapizVentanas), "solucionNodos", TapizVentanas.solucionNodosDomainPropertyId, typeof(TapizVentanas.solucionNodosPropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "nombre", Ventana.nombreDomainPropertyId, typeof(Ventana.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "altoCalculada", Ventana.altoCalculadaDomainPropertyId, typeof(Ventana.altoCalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "anchoCalculada", Ventana.anchoCalculadaDomainPropertyId, typeof(Ventana.anchoCalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "alto", Ventana.altoDomainPropertyId, typeof(Ventana.altoPropertyHandler)),
				new DomainMemberInfo(typeof(Ventana), "ancho", Ventana.anchoDomainPropertyId, typeof(Ventana.anchoPropertyHandler)),
				new DomainMemberInfo(typeof(VentanaSecundaria), "modal", VentanaSecundaria.modalDomainPropertyId, typeof(VentanaSecundaria.modalPropertyHandler)),
				new DomainMemberInfo(typeof(VentanaSecundaria), "modalCalculada", VentanaSecundaria.modalCalculadaDomainPropertyId, typeof(VentanaSecundaria.modalCalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(Menu), "nombre", Menu.nombreDomainPropertyId, typeof(Menu.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Item), "titulo", Item.tituloDomainPropertyId, typeof(Item.tituloPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "Color", Clase.ColorDomainPropertyId, typeof(Clase.ColorPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "ColorFondo", Clase.ColorFondoDomainPropertyId, typeof(Clase.ColorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "TipoLetra", Clase.TipoLetraDomainPropertyId, typeof(Clase.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "Nombre", Clase.NombreDomainPropertyId, typeof(Clase.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(EntradaDeDatos), "Titulo", EntradaDeDatos.TituloDomainPropertyId, typeof(EntradaDeDatos.TituloPropertyHandler)),
				new DomainMemberInfo(typeof(EntradaDeDatos), "Texto", EntradaDeDatos.TextoDomainPropertyId, typeof(EntradaDeDatos.TextoPropertyHandler)),
				new DomainMemberInfo(typeof(AreaDeTexto), "Disposicion", AreaDeTexto.DisposicionDomainPropertyId, typeof(AreaDeTexto.DisposicionPropertyHandler)),
				new DomainMemberInfo(typeof(Componente), "Nombre", Componente.NombreDomainPropertyId, typeof(Componente.NombrePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizVentanasHasVentanaPrincipal), "TapizVentanas", TapizVentanasHasVentanaPrincipal.TapizVentanasDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizVentanasHasVentanaPrincipal), "VentanaPrincipal", TapizVentanasHasVentanaPrincipal.VentanaPrincipalDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizVentanasHasVentanaSecundaria), "TapizVentanas", TapizVentanasHasVentanaSecundaria.TapizVentanasDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizVentanasHasVentanaSecundaria), "VentanaSecundaria", TapizVentanasHasVentanaSecundaria.VentanaSecundariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasBotonPertenece), "Ventana", VentanaHasBotonPertenece.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasBotonPertenece), "Boton", VentanaHasBotonPertenece.BotonDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasMenuPertenece), "Ventana", VentanaHasMenuPertenece.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasMenuPertenece), "Menu", VentanaHasMenuPertenece.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(MenuHasItemPerteneceMenu), "Menu", MenuHasItemPerteneceMenu.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(MenuHasItemPerteneceMenu), "ItemMenu", MenuHasItemPerteneceMenu.ItemMenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemReferencesVentana), "Item", ItemReferencesVentana.ItemDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemReferencesVentana), "Ventana", ItemReferencesVentana.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizVentanasHasEstadoFinal), "TapizVentanas", TapizVentanasHasEstadoFinal.TapizVentanasDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizVentanasHasEstadoFinal), "EstadoFinal", TapizVentanasHasEstadoFinal.EstadoFinalDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemReferencesEstadoFinal), "Item", ItemReferencesEstadoFinal.ItemDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemReferencesEstadoFinal), "EstadoFinal", ItemReferencesEstadoFinal.EstadoFinalDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemReferencesClase), "Item", ItemReferencesClase.ItemDomainRoleId),
				new DomainRolePlayerInfo(typeof(ItemReferencesClase), "Clase", ItemReferencesClase.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizVentanasHasClase), "TapizVentanas", TapizVentanasHasClase.TapizVentanasDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizVentanasHasClase), "Clase", TapizVentanasHasClase.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesVentana4), "Clase", ClaseReferencesVentana4.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesVentana4), "Ventana", ClaseReferencesVentana4.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesItem4), "Clase", ClaseReferencesItem4.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesItem4), "Item", ClaseReferencesItem4.ItemDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesMenu4), "Clase", ClaseReferencesMenu4.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesMenu4), "Menu", ClaseReferencesMenu4.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasEntradaDeDatos), "Ventana", VentanaHasEntradaDeDatos.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasEntradaDeDatos), "EntradaDeDatos", VentanaHasEntradaDeDatos.EntradaDeDatosDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasComponente), "Ventana", VentanaHasComponente.VentanaDomainRoleId),
				new DomainRolePlayerInfo(typeof(VentanaHasComponente), "Componente", VentanaHasComponente.ComponenteDomainRoleId),
				new DomainRolePlayerInfo(typeof(ComponenteReferencesItem), "Componente", ComponenteReferencesItem.ComponenteDomainRoleId),
				new DomainRolePlayerInfo(typeof(ComponenteReferencesItem), "Item", ComponenteReferencesItem.ItemDomainRoleId),
				new DomainRolePlayerInfo(typeof(ComponenteReferencesEntradaDeDatos), "Componente", ComponenteReferencesEntradaDeDatos.ComponenteDomainRoleId),
				new DomainRolePlayerInfo(typeof(ComponenteReferencesEntradaDeDatos), "EntradaDeDatos", ComponenteReferencesEntradaDeDatos.EntradaDeDatosDomainRoleId),
				new DomainRolePlayerInfo(typeof(ComponenteReferencesMenu), "Componente", ComponenteReferencesMenu.ComponenteDomainRoleId),
				new DomainRolePlayerInfo(typeof(ComponenteReferencesMenu), "Menu", ComponenteReferencesMenu.MenuDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesComponente), "Clase", ClaseReferencesComponente.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesComponente), "Componente", ClaseReferencesComponente.ComponenteDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesEntradaDeDatos), "Clase", ClaseReferencesEntradaDeDatos.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesEntradaDeDatos), "EntradaDeDatos", ClaseReferencesEntradaDeDatos.EntradaDeDatosDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(31);
				createElementMap.Add(typeof(TapizVentanas), 0);
				createElementMap.Add(typeof(VentanaPrincipal), 1);
				createElementMap.Add(typeof(VentanaSecundaria), 2);
				createElementMap.Add(typeof(Boton), 3);
				createElementMap.Add(typeof(Menu), 4);
				createElementMap.Add(typeof(ItemMenu), 5);
				createElementMap.Add(typeof(EstadoFinal), 6);
				createElementMap.Add(typeof(Clase), 7);
				createElementMap.Add(typeof(CampoDeTexto), 8);
				createElementMap.Add(typeof(AreaDeTexto), 9);
				createElementMap.Add(typeof(CheckBox), 10);
				createElementMap.Add(typeof(Componente), 11);
				createElementMap.Add(typeof(IGGORCJCFProyectoIPSDiagram), 12);
				createElementMap.Add(typeof(MetaforaItem_Ventana), 13);
				createElementMap.Add(typeof(MetaforaEstadoFinal_Item), 14);
				createElementMap.Add(typeof(MetaforaClase_Elementos), 15);
				createElementMap.Add(typeof(ComponenteConnector), 16);
				createElementMap.Add(typeof(ComponenteMetafora), 17);
				createElementMap.Add(typeof(VentanaSecMetafora), 18);
				createElementMap.Add(typeof(VentanaPrinMetafora), 19);
				createElementMap.Add(typeof(MenuMetafora), 20);
				createElementMap.Add(typeof(BotonMetafora), 21);
				createElementMap.Add(typeof(ItemMenuMetafora), 22);
				createElementMap.Add(typeof(MetaforaEstadoFinal), 23);
				createElementMap.Add(typeof(ClaseMetafora), 24);
				createElementMap.Add(typeof(CampoDeTextoMetafora), 25);
				createElementMap.Add(typeof(AreaDeTextoMetafora), 26);
				createElementMap.Add(typeof(CheckboxMetafora), 27);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new TapizVentanas(partition, propertyAssignments);
				case 1: return new VentanaPrincipal(partition, propertyAssignments);
				case 2: return new VentanaSecundaria(partition, propertyAssignments);
				case 3: return new Boton(partition, propertyAssignments);
				case 4: return new Menu(partition, propertyAssignments);
				case 5: return new ItemMenu(partition, propertyAssignments);
				case 6: return new EstadoFinal(partition, propertyAssignments);
				case 7: return new Clase(partition, propertyAssignments);
				case 8: return new CampoDeTexto(partition, propertyAssignments);
				case 9: return new AreaDeTexto(partition, propertyAssignments);
				case 10: return new CheckBox(partition, propertyAssignments);
				case 11: return new Componente(partition, propertyAssignments);
				case 12: return new IGGORCJCFProyectoIPSDiagram(partition, propertyAssignments);
				case 13: return new MetaforaItem_Ventana(partition, propertyAssignments);
				case 14: return new MetaforaEstadoFinal_Item(partition, propertyAssignments);
				case 15: return new MetaforaClase_Elementos(partition, propertyAssignments);
				case 16: return new ComponenteConnector(partition, propertyAssignments);
				case 17: return new ComponenteMetafora(partition, propertyAssignments);
				case 18: return new VentanaSecMetafora(partition, propertyAssignments);
				case 19: return new VentanaPrinMetafora(partition, propertyAssignments);
				case 20: return new MenuMetafora(partition, propertyAssignments);
				case 21: return new BotonMetafora(partition, propertyAssignments);
				case 22: return new ItemMenuMetafora(partition, propertyAssignments);
				case 23: return new MetaforaEstadoFinal(partition, propertyAssignments);
				case 24: return new ClaseMetafora(partition, propertyAssignments);
				case 25: return new CampoDeTextoMetafora(partition, propertyAssignments);
				case 26: return new AreaDeTextoMetafora(partition, propertyAssignments);
				case 27: return new CheckboxMetafora(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(20);
				createElementLinkMap.Add(typeof(TapizVentanasHasVentanaPrincipal), 0);
				createElementLinkMap.Add(typeof(TapizVentanasHasVentanaSecundaria), 1);
				createElementLinkMap.Add(typeof(VentanaHasBotonPertenece), 2);
				createElementLinkMap.Add(typeof(VentanaHasMenuPertenece), 3);
				createElementLinkMap.Add(typeof(MenuHasItemPerteneceMenu), 4);
				createElementLinkMap.Add(typeof(ItemReferencesVentana), 5);
				createElementLinkMap.Add(typeof(TapizVentanasHasEstadoFinal), 6);
				createElementLinkMap.Add(typeof(ItemReferencesEstadoFinal), 7);
				createElementLinkMap.Add(typeof(ItemReferencesClase), 8);
				createElementLinkMap.Add(typeof(TapizVentanasHasClase), 9);
				createElementLinkMap.Add(typeof(ClaseReferencesVentana4), 10);
				createElementLinkMap.Add(typeof(ClaseReferencesItem4), 11);
				createElementLinkMap.Add(typeof(ClaseReferencesMenu4), 12);
				createElementLinkMap.Add(typeof(VentanaHasEntradaDeDatos), 13);
				createElementLinkMap.Add(typeof(VentanaHasComponente), 14);
				createElementLinkMap.Add(typeof(ComponenteReferencesItem), 15);
				createElementLinkMap.Add(typeof(ComponenteReferencesEntradaDeDatos), 16);
				createElementLinkMap.Add(typeof(ComponenteReferencesMenu), 17);
				createElementLinkMap.Add(typeof(ClaseReferencesComponente), 18);
				createElementLinkMap.Add(typeof(ClaseReferencesEntradaDeDatos), 19);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizVentanasHasVentanaPrincipal(partition, roleAssignments, propertyAssignments);
				case 1: return new TapizVentanasHasVentanaSecundaria(partition, roleAssignments, propertyAssignments);
				case 2: return new VentanaHasBotonPertenece(partition, roleAssignments, propertyAssignments);
				case 3: return new VentanaHasMenuPertenece(partition, roleAssignments, propertyAssignments);
				case 4: return new MenuHasItemPerteneceMenu(partition, roleAssignments, propertyAssignments);
				case 5: return new ItemReferencesVentana(partition, roleAssignments, propertyAssignments);
				case 6: return new TapizVentanasHasEstadoFinal(partition, roleAssignments, propertyAssignments);
				case 7: return new ItemReferencesEstadoFinal(partition, roleAssignments, propertyAssignments);
				case 8: return new ItemReferencesClase(partition, roleAssignments, propertyAssignments);
				case 9: return new TapizVentanasHasClase(partition, roleAssignments, propertyAssignments);
				case 10: return new ClaseReferencesVentana4(partition, roleAssignments, propertyAssignments);
				case 11: return new ClaseReferencesItem4(partition, roleAssignments, propertyAssignments);
				case 12: return new ClaseReferencesMenu4(partition, roleAssignments, propertyAssignments);
				case 13: return new VentanaHasEntradaDeDatos(partition, roleAssignments, propertyAssignments);
				case 14: return new VentanaHasComponente(partition, roleAssignments, propertyAssignments);
				case 15: return new ComponenteReferencesItem(partition, roleAssignments, propertyAssignments);
				case 16: return new ComponenteReferencesEntradaDeDatos(partition, roleAssignments, propertyAssignments);
				case 17: return new ComponenteReferencesMenu(partition, roleAssignments, propertyAssignments);
				case 18: return new ClaseReferencesComponente(partition, roleAssignments, propertyAssignments);
				case 19: return new ClaseReferencesEntradaDeDatos(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return IGGORCJCFProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (IGGORCJCFProyectoIPSDomainModel.resourceManager == null)
				{
					IGGORCJCFProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(IGGORCJCFProyectoIPSDomainModel).Assembly);
				}
				return IGGORCJCFProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return IGGORCJCFProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return IGGORCJCFProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (IGGORCJCFProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new IGGORCJCFProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					IGGORCJCFProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return IGGORCJCFProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (IGGORCJCFProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new IGGORCJCFProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					IGGORCJCFProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return IGGORCJCFProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IGGORCJCFProyectoIPSDeleteClosure : IGGORCJCFProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IGGORCJCFProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IGGORCJCFProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public IGGORCJCFProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanasHasVentanaPrincipal.VentanaPrincipalDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanasHasVentanaSecundaria.VentanaSecundariaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaHasBotonPertenece.BotonDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaHasMenuPertenece.MenuDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.MenuHasItemPerteneceMenu.ItemMenuDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanasHasEstadoFinal.EstadoFinalDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.TapizVentanasHasClase.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaHasEntradaDeDatos.EntradaDeDatosDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaHasComponente.ComponenteDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IGGORCJCFProyectoIPSCopyClosure : IGGORCJCFProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IGGORCJCFProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IGGORCJCFProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IGGORCJCFProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoDelLetra
	/// Description for UPM_IPS.IGGORCJCFProyectoIPS.TipoDelLetra
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoDelLetra
	{
		/// <summary>
		/// TimesNewRoman
		/// Description for UPM_IPS.IGGORCJCFProyectoIPS.TipoDelLetra.TimesNewRoman
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.IGGORCJCFProyectoIPS.TipoDelLetra/TimesNewRoman.Description", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
		TimesNewRoman = 2,
		/// <summary>
		/// SansSerif
		/// Description for UPM_IPS.IGGORCJCFProyectoIPS.TipoDelLetra.SansSerif
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.IGGORCJCFProyectoIPS.TipoDelLetra/SansSerif.Description", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
		SansSerif = 1,
		/// <summary>
		/// Arial
		/// Description for UPM_IPS.IGGORCJCFProyectoIPS.TipoDelLetra.Arial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.IGGORCJCFProyectoIPS.TipoDelLetra/Arial.Description", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
		Arial = 0,
	}
}
namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Disposicion
	/// Description for UPM_IPS.IGGORCJCFProyectoIPS.Disposicion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Disposicion
	{
		/// <summary>
		/// UnaColumna
		/// Description for UPM_IPS.IGGORCJCFProyectoIPS.Disposicion.UnaColumna
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.IGGORCJCFProyectoIPS.Disposicion/UnaColumna.Description", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
		UnaColumna = 0,
		/// <summary>
		/// DosColumnas
		/// Description for UPM_IPS.IGGORCJCFProyectoIPS.Disposicion.DosColumnas
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.IGGORCJCFProyectoIPS.Disposicion/DosColumnas.Description", typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel), "UPM_IPS.IGGORCJCFProyectoIPS.GeneratedCode.DomainModelResx")]
		DosColumnas = 1,
	}
}

