//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class IGGORCJCFProyectoIPSToolboxHelper : IGGORCJCFProyectoIPSToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new IGGORCJCFProyectoIPSToolboxHelper.
		/// </summary>
		public IGGORCJCFProyectoIPSToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class IGGORCJCFProyectoIPSToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify IGGORCJCFProyectoIPS toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "IGGORCJCFProyectoIPS.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceItem_VentanaTool connector tool.
		/// </summary>
		public const string EnlaceItem_VentanaToolFilterString = "EnlaceItem_VentanaTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceEstadoFinal_ItemTool connector tool.
		/// </summary>
		public const string EnlaceEstadoFinal_ItemToolFilterString = "EnlaceEstadoFinal_ItemTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceClase_Ventana connector tool.
		/// </summary>
		public const string EnlaceClase_VentanaFilterString = "EnlaceClase_Ventana.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceClase_Item connector tool.
		/// </summary>
		public const string EnlaceClase_ItemFilterString = "EnlaceClase_Item.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceClase_Menu connector tool.
		/// </summary>
		public const string EnlaceClase_MenuFilterString = "EnlaceClase_Menu.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceClase_Componente connector tool.
		/// </summary>
		public const string EnlaceClase_ComponenteFilterString = "EnlaceClase_Componente.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceClase_EntradaDeDatos connector tool.
		/// </summary>
		public const string EnlaceClase_EntradaDeDatosFilterString = "EnlaceClase_EntradaDeDatos.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceComponente_item connector tool.
		/// </summary>
		public const string EnlaceComponente_itemFilterString = "EnlaceComponente_item.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceComponente_EntradaDeDatos connector tool.
		/// </summary>
		public const string EnlaceComponente_EntradaDeDatosFilterString = "EnlaceComponente_EntradaDeDatos.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EnlaceComponente_Menu connector tool.
		/// </summary>
		public const string EnlaceComponente_MenuFilterString = "EnlaceComponente_Menu.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new IGGORCJCFProyectoIPSToolboxHelperBase.
		/// </summary>
		protected IGGORCJCFProyectoIPSToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel.SingletonResourceManager.GetString("EnlacesToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 10;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceItem_VentanaToolToolboxItem":

					// Add EnlaceItem_VentanaTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceItem_VentanaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceItem_VentanaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceItem_VentanaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceItem_VentanaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceItem_VentanaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceItem_VentanaToolFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceEstadoFinal_ItemToolToolboxItem":

					// Add EnlaceEstadoFinal_ItemTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceEstadoFinal_ItemToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceEstadoFinal_ItemToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceEstadoFinal_ItemToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceEstadoFinal_ItemTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceEstadoFinal_ItemToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceEstadoFinal_ItemToolFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_VentanaToolboxItem":

					// Add EnlaceClase_Ventana connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_VentanaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceClase_VentanaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceClase_VentanaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceClase_VentanaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceClase_VentanaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceClase_VentanaFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ItemToolboxItem":

					// Add EnlaceClase_Item connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ItemToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceClase_ItemToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceClase_ItemToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceClase_ItemTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceClase_ItemToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceClase_ItemFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_MenuToolboxItem":

					// Add EnlaceClase_Menu connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_MenuToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceClase_MenuToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceClase_MenuToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceClase_MenuTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceClase_MenuToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceClase_MenuFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ComponenteToolboxItem":

					// Add EnlaceClase_Componente connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ComponenteToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceClase_ComponenteToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceClase_ComponenteToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceClase_Componente", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceClase_ComponenteToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceClase_ComponenteFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_EntradaDeDatosToolboxItem":

					// Add EnlaceClase_EntradaDeDatos connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_EntradaDeDatosToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceClase_EntradaDeDatosToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceClase_EntradaDeDatosToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceClase_EntradaDeDatos", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceClase_EntradaDeDatosToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceClase_EntradaDeDatosFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_itemToolboxItem":

					// Add EnlaceComponente_item connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_itemToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceComponente_itemToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceComponente_itemToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceComponente_item", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceComponente_itemToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceComponente_itemFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_EntradaDeDatosToolboxItem":

					// Add EnlaceComponente_EntradaDeDatos connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_EntradaDeDatosToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceComponente_EntradaDeDatosToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceComponente_EntradaDeDatosToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceComponente_EntradaDeDatos", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceComponente_EntradaDeDatosToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceComponente_EntradaDeDatosFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_MenuToolboxItem":

					// Add EnlaceComponente_Menu connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_MenuToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EnlaceComponente_MenuToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EnlaceComponente_MenuToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EnlaceComponente_Menu", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EnlaceComponente_MenuToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EnlaceComponente_MenuFilterString)
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipalToolToolboxItem":
					// Add VentanaPrincipalTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipalToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("VentanaPrincipalToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("VentanaPrincipalToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.VentanasToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VentanasToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"VentanaPrincipalTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("VentanaPrincipalToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipal.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundariaToolToolboxItem":
					// Add VentanaSecundariaTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundariaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("VentanaSecundariaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("VentanaSecundariaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.VentanasToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("VentanasToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"VentanaSecundariaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("VentanaSecundariaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundaria.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.BotonToolToolboxItem":
					// Add BotonTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.BotonToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("BotonToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("BotonToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObligatoriasToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"BotonTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("BotonToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.Boton.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.MenuToolToolboxItem":
					// Add MenuTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.MenuToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("MenuToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("MenuToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObligatoriasToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"MenuTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("MenuToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.Menu.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.ItemMenuToolToolboxItem":
					// Add ItemMenuTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.ItemMenuToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ItemMenuToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ItemMenuToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObligatoriasToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ItemMenuTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ItemMenuToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.ItemMenu.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinalToolToolboxItem":
					// Add EstadoFinalTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinalToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EstadoFinalToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EstadoFinalToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObligatoriasToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EstadoFinalTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EstadoFinalToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinal.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.ClaseToolToolboxItem":
					// Add ClaseTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.ClaseToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ClaseToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ClaseToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ExtraToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ClaseTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ClaseToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.Clase.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoToolToolboxItem":
					// Add AreaDeTextoTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AreaDeTextoToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AreaDeTextoToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ExtraToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AreaDeTextoTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AreaDeTextoToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTexto.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoToolToolboxItem":
					// Add CampoDeTextoTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CampoDeTextoToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CampoDeTextoToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ExtraToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CampoDeTextoTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CampoDeTextoToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTexto.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.CheckBoxToolToolboxItem":
					// Add CheckBoxTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.CheckBoxToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CheckBoxToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CheckBoxToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ExtraToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CheckBoxTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CheckBoxToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.CheckBox.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.IGGORCJCFProyectoIPS.ComponenteToolToolboxItem":
					// Add ComponenteTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.IGGORCJCFProyectoIPS.ComponenteToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ComponenteToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ComponenteToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ExtraToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ComponenteTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ComponenteToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.IGGORCJCFProyectoIPS.Componente.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
