//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "IGGORCJCFProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"IGGORCJCFProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID IGGORCJCFProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IGGORCJCFProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID IGGORCJCFProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IGGORCJCFProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewIGGORCJCFProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(IGGORCJCFProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string IGGORCJCFProyectoIPSPackageId = "8491a999-3690-4260-ae75-43afeb1e1a3a";
		
		// Editor factory identifier
		public const string IGGORCJCFProyectoIPSEditorFactoryId = "db043092-1069-48c5-91f2-65adc2da562b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string IGGORCJCFProyectoIPSModelExplorerToolWindowId = "a0a5e928-abb7-4c3f-ba31-9ccaadaa811a";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string IGGORCJCFProyectoIPSCommandSetId = "8ae86cee-2b0e-4f4c-a5da-48bfdeb7f5c5";
	}
}