//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(IGGORCJCFProyectoIPSExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(IGGORCJCFProyectoIPSExplorerToolWindow), Constants.IGGORCJCFProyectoIPSEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@EnlacesToolboxTab;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", "UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceItem_VentanaToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceItem_VentanaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceItem_VentanaTool", 
					"@EnlaceItem_VentanaToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceEstadoFinal_ItemToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceEstadoFinal_ItemToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceEstadoFinal_ItemTool", 
					"@EnlaceEstadoFinal_ItemToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceClase_VentanaToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_VentanaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceClase_VentanaTool", 
					"@EnlaceClase_VentanaToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceClase_ItemToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ItemToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceClase_ItemTool", 
					"@EnlaceClase_ItemToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceClase_MenuToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_MenuToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceClase_MenuTool", 
					"@EnlaceClase_MenuToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceClase_ComponenteToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_ComponenteToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceClase_Componente", 
					"@EnlaceClase_ComponenteToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceClase_EntradaDeDatosToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceClase_EntradaDeDatosToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceClase_EntradaDeDatos", 
					"@EnlaceClase_EntradaDeDatosToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceComponente_itemToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_itemToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceComponente_item", 
					"@EnlaceComponente_itemToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceComponente_EntradaDeDatosToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_EntradaDeDatosToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceComponente_EntradaDeDatos", 
					"@EnlaceComponente_EntradaDeDatosToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.EnlacesToolboxTab",
					"@EnlaceComponente_MenuToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EnlaceComponente_MenuToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EnlaceComponente_Menu", 
					"@EnlaceComponente_MenuToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxGroup("@VentanasToolboxTab;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", "UPM_IPS.IGGORCJCFProyectoIPS.VentanasToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.VentanasToolboxTab",
					"@VentanaPrincipalToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.VentanaPrincipalToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"VentanaPrincipalTool", 
					"@VentanaPrincipalToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.VentanasToolboxTab",
					"@VentanaSecundariaToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.VentanaSecundariaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"VentanaSecundariaTool", 
					"@VentanaSecundariaToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxGroup("@ObligatoriasToolboxTab;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", "UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab",
					"@BotonToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.BotonToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"BotonTool", 
					"@BotonToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab",
					"@MenuToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.MenuToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"MenuTool", 
					"@MenuToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab",
					"@ItemMenuToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.ItemMenuToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ItemMenuTool", 
					"@ItemMenuToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ObligatoriasToolboxTab",
					"@EstadoFinalToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.EstadoFinalToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EstadoFinalTool", 
					"@EstadoFinalToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxGroup("@ExtraToolboxTab;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", "UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab",
					"@ClaseToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.ClaseToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ClaseTool", 
					"@ClaseToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab",
					"@AreaDeTextoToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.AreaDeTextoToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AreaDeTextoTool", 
					"@AreaDeTextoToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 17)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab",
					"@CampoDeTextoToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.CampoDeTextoToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CampoDeTextoTool", 
					"@CampoDeTextoToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 18)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab",
					"@CheckBoxToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.CheckBoxToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CheckBoxTool", 
					"@CheckBoxToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 19)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.IGGORCJCFProyectoIPS.ExtraToolboxTab",
					"@ComponenteToolToolboxItem;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					"UPM_IPS.IGGORCJCFProyectoIPS.ComponenteToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ComponenteTool", 
					"@ComponenteToolToolboxBitmap;UPM_IPS.IGGORCJCFProyectoIPS.Dsl.dll", 
					0xff00ff,
					Index = 20)]
	[VSShell::ProvideEditorFactory(typeof(IGGORCJCFProyectoIPSEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(IGGORCJCFProyectoIPSEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(IGGORCJCFProyectoIPSEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"IGGORCJCFProyectoIPS", typeof(IGGORCJCFProyectoIPSEditorFactory))]

	internal abstract partial class IGGORCJCFProyectoIPSPackageBase : DslShell::AsyncModelingPackage
	{
		protected global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new IGGORCJCFProyectoIPSEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			IGGORCJCFProyectoIPSCommandSet commandSet = new IGGORCJCFProyectoIPSCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			IGGORCJCFProyectoIPSClipboardCommandSet clipboardCommandSet = new IGGORCJCFProyectoIPSClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(IGGORCJCFProyectoIPSExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(IGGORCJCFProyectoIPSExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace UPM_IPS.IGGORCJCFProyectoIPS
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDirectiveProcessor), global::UPM_IPS.IGGORCJCFProyectoIPS.IGGORCJCFProyectoIPSDirectiveProcessor.IGGORCJCFProyectoIPSDirectiveProcessorName, "A directive processor that provides access to IGGORCJCFProyectoIPS files")]
	[global::System.Runtime.InteropServices.Guid(Constants.IGGORCJCFProyectoIPSPackageId)]
	internal sealed partial class IGGORCJCFProyectoIPSPackage : IGGORCJCFProyectoIPSPackageBase
	{
	}
}